In [1]:
# 추천 기준: 공원, 영화관
# 집값: 1억~3억
# 근무지: 숙명여대
# 통근시간: 버스or 지하철 60분 이내

In [16]:
import pandas as pd
from sklearn import preprocessing
from sklearn.metrics.pairwise import euclidean_distances
from sklearn.metrics.pairwise import cosine_similarity
import time
import json
import os
import ssl
import urllib.request
#df = pd.read_csv('./train_all.csv')

In [83]:
def transit_api(address, transit, origin_list): #
    destination = address
    mode = 'transit'
    transit_mode =transit[0]
    limit_time = transit[1]
    
    filtered_idx = {}
    idx_content={}


    #if (__name__ == "__main__"):
        #client = None
    with open("./google_key.json","r") as clientJson :
        client = json.load(clientJson)
        print('완료1')
        print(origin_list)

    for origin in origin_list:
        if len(filtered_idx) < 3:

            departure_time  = "1640818800" #2021 12 30 AM8:00 TIMESTAMP
            key             = client['key']
            print('완료2')

            url = "https://maps.googleapis.com/maps/api/directions/json?origin="+ origin + "&destination=" + destination + "&mode=" + mode+ "&transit_mode="+ transit_mode + "&departure_time=" + departure_time + "&language=ko"+ "&key=" + key

            request         = urllib.request.Request(url)
            context         = ssl._create_unverified_context()
            response        = urllib.request.urlopen(request, context=context)
            responseText    = response.read().decode('utf-8')
            content    = json.loads(responseText)
            #print(content)
            path   = content["routes"][0]["legs"][0]
            duration_sec  = path["duration"]["value"]
            #print(duration_sec)
            if duration_sec <= (limit_time*60):
                filtered_idx[origin] = duration_sec
                print('완료3')
                idx_content[len(filtered_idx)] = content
                with open("./result2.json","w") as json_file:
                    json.dump(idx_content, json_file, indent=4)
                    print('완료4')
    return filtered_idx 

def recommend(address, price, transit, options): #['영화관','도서관']
    df = pd.read_csv('./train_all.csv')
    col = ['address']
    for i in range(len(options)):
        col.append(options[i])
    print(col)
    for i in range(len(col)):
        idx = df[df[col[i]] == 0].index
        df=df.drop(idx)
    data = df.copy()

    data = df.copy()
    data = data[col]
    data = data.set_index('address')
    
    data_max= data.iloc[:,:5].max(axis=0)
    data_max['address'] = '비교'
    data = data.reset_index(drop=False)
    data = data[col].append(data_max, ignore_index=True)
    data = data.set_index('address')
    
    col.append('공시가격')
    col.append('좌표')
    data_ = df[col]

    data_max_= data_.iloc[:,:6].max(axis=0)
    data_max_['address'] = '비교'
    data_ = data_[col].append(data_max_, ignore_index=True)
    data_ = data_.set_index('address')
    
    
    scaler = preprocessing.MinMaxScaler()
    data[data.columns] = scaler.fit_transform(data[data.columns])
    print(data)
    euclidean = euclidean_distances(data ,data)
    distance = euclidean[-1, :].reshape(-1)
    
    data = data.reset_index(drop=False)
    index_distance = {}
    for idx, val in enumerate(distance):
        index_distance[idx] = val

    for i in range(len(index_distance)):
        #index = index_distance[i][0]
        distance = index_distance[i]
        data.loc[i,'distance'] = distance
    dc = data.sort_values(by='distance', ascending=True)
    dc = dc.set_index('address')
    print(dc)
    data2 = dc[['distance']]
    
    data2 = data2.join(data_)
    data2 = data2.fillna(0)
    comp = data2.iloc[0]
    print(comp)
    
    data2 = data2.drop('비교')
    print('data2', data2)
    
    #price = [1,3]
    condition = (data2['공시가격'] > price[0]) &(data2['공시가격'] < price[1])
    price_data = data2[condition]
    
    origin_list = price_data['좌표'].tolist()
    print(origin_list)
    filtered_idx = transit_api(address, transit, origin_list)
    print(filtered_idx)
    
    comp = comp.to_frame()
    comp =comp.T
    for i in range(len(filtered_idx)):
        comp = comp.append(price_data[(price_data['좌표']==(list(filtered_idx.keys())[i]))])
    
    comp['공시가격'][0] = price
    comp['좌표'][0] = address
    comp['교통편']=0
    trans = list(filtered_idx.values())
    for i in range(len(filtered_idx)):
        comp['교통편'][i+1]= trans[i]
    comp['교통편'][0] = transit[1]*60
    #comp.to_csv('./교통추천결과값4.csv',encoding='euc-kr')
    result = comp.to_json()
    print(comp)
    return result
    

    #destination = '37.546475,126.964692'
    #mode = 'transit'
    #transit_mode = 'bus|subway'
    #limit_time = 60

In [84]:
#def recommend(address, price, transit, options)
result = recommend('37.546475,126.964692', [0,3000000000], ['bus', 60], ['공원','영화관','초등학교'])

['address', '공원', '영화관', '초등학교']
                     공원       영화관      초등학교
address
서울특별시 강남구 논현동  0.161290  1.000000  0.071429
서울특별시 강남구 도곡동  0.258065  0.000000  0.071429
서울특별시 강남구 삼성동  0.064516  0.166667  0.071429
서울특별시 강남구 신사동  0.000000  0.333333  0.000000
서울특별시 강남구 역삼동  0.322581  0.583333  0.071429
...                 ...       ...       ...
인천광역시 계양구 작전동  0.161290  0.166667  0.214286
인천광역시 서구 연희동   0.064516  0.000000  0.000000
인천광역시 서구 당하동   0.000000  0.000000  0.142857
인천광역시 서구 청라동   0.354839  0.083333  0.428571
비교             1.000000  1.000000  1.000000

[135 rows x 3 columns]
                       공원       영화관      초등학교  distance
address
비교               1.000000  1.000000  1.000000  0.000000
인천광역시 연수구 송도동    1.000000  0.166667  1.000000  0.833333
경기도 시흥시 정왕동      0.838710  0.500000  0.142857  1.005340
인천광역시 남동구 논현동    0.354839  0.166667  0.571429  1.137695
경기도 부천시 중동       0.451613  0.166667  0.428571  1.149654
...                   ...       ...       ...       ...
경기도 포천시 영북면 운천리  0.000000  0.000000  0.000000  1.732051
서울특별시 영등포구 영등포동  0.000000  0.000000  0.000000  1.732051
서울특별시 서대문구 연희동   0.000000  0.000000  0.000000  1.732051
서울특별시 서대문구 대현동   0.000000  0.000000  0.000000  1.732051
서울특별시 마포구 서교동    0.000000  0.000000  0.000000  1.732051

[135 rows x 4 columns]
distance                     0.0
공원                            32
영화관                           13
초등학교                          15
공시가격                2130358888.0
좌표          38.089184,127.272418
Name: 비교, dtype: object
data2                  distance  공원  영화관  초등학교          공시가격                    좌표
address
인천광역시 연수구 송도동    0.833333  32    3    15  3.946582e+08  37.384532,126.645656
경기도 시흥시 정왕동      1.005340  27    7     3  1.428391e+08  37.342152,126.730792
인천광역시 남동구 논현동    1.137695  12    3     9  1.705401e+08  37.404763,126.722968
경기도 부천시 중동       1.149654  15    3     7  2.407290e+08  37.496645,126.769864
경기도 수원시 영통구 영통동  1.166481  12    3     8  2.183923e+08  37.252109,127.074216
...                   ...  ..  ...   ...           ...                   ...
경기도 포천시 영북면 운천리  1.732051   1    1     1  2.340495e+07  38.089184,127.272418
서울특별시 영등포구 영등포동  1.732051   1    1     1  8.014599e+08  37.513448,126.907724
서울특별시 서대문구 연희동   1.732051   1    1     1  4.599138e+08  37.570389,126.929628
서울특별시 서대문구 대현동   1.732051   1    1     1  4.012191e+08  37.558086,126.944504
서울특별시 마포구 서교동    1.732051   1    1     1  9.722019e+08  37.553910,126.918985

[134 rows x 6 columns]
['37.384532,126.645656', '37.342152,126.730792', '37.404763,126.722968', '37.496645,126.769864', '37.252109,127.074216', '37.320881,126.831077', '37.394613,126.921797', '37.273035,126.950265', '37.500335,127.037596', '37.609643,127.159930', '37.621298,127.024902', '37.257198,127.026007', '37.513093,127.031353', '37.533120,126.640323', '37.493656,126.724134', '37.329829,127.118405', '37.620895,126.838836', '37.638099,126.833358', '37.377235,126.955595', '37.675936,126.748116', '37.643440,127.039413', '37.454866,126.679934', '37.644355,126.936524', '37.486581,127.127495', '37.476412,126.925691', '37.302677,127.079417', '37.539776,126.869079', '37.739252,127.046582', '37.482717,126.949951', '37.469371,126.901246', '37.411694,126.662205', '37.817819,127.089813', '37.551325,126.858411', '37.269945,127.157540', '36.997315,127.100913', '37.450744,126.710499', '37.403080,126.965817', '37.607493,127.135196', '37.534692,127.074327', '37.530552,126.726859', '37.659408,127.116765', '37.654307,126.681501', '37.489897,126.491849', '37.644653,126.766178', '37.538358,126.847336', '37.483974,126.974999', '37.495752,126.755957', '37.492900,126.886427', '37.235585,127.203674', '37.695744,126.743289', '37.558584,126.934113', '37.720182,127.206285', '37.277083,127.118730', '37.644500,126.786140', '37.410279,127.136318', '37.297806,127.048455', '37.671126,126.761620', '37.639388,127.017183', '37.343651,127.115831', '37.569138,126.812192', '37.570749,127.068233', '37.517302,127.104967', '37.905694,127.056669', '37.524659,126.963299', '37.503478,126.553969', '37.318759,127.062055', '37.502816,127.010493', '37.486509,127.040738', '37.488514,127.016222', '37.512792,127.053085', '37.494970,126.851409', '37.605253,126.929107', '37.469235,126.822368', '37.522893,127.028589', '37.299724,127.015538', '37.381670,127.133860', '37.544661,127.046772', '37.268422,126.987411', '37.606151,126.723874', '37.323259,126.846872', '37.598415,127.020288', '37.579797,127.053848', '37.563317,126.910870', '37.830702,127.143594', '37.467073,127.142925', '37.566092,126.830395', '37.517028,126.702209', '37.531338,127.129174', '37.237878,127.190672', '37.467383,126.666387', '37.612276,126.922850', '37.269442,127.025008', '37.293490,127.147352', '37.779440,126.704771', '37.611266,127.077829', '37.424062,126.652109', '37.442015,126.663750', '37.206884,127.039407', '37.266765,127.106933', '37.221344,126.959183', '37.635123,127.032072', '37.513667,127.016166', '37.524371,126.925958', '37.589907,126.683700', '37.544655,127.089493', '37.656327,127.307680', '37.297648,126.977745', '37.104534,126.916966', '37.638168,126.710953', '37.433173,127.136241', '37.384354,127.108486', '37.255024,127.110297', '37.559076,127.035869', '37.642888,126.626692', '37.491515,127.491608', '37.480629,126.864415', '37.867703,126.775760', '37.187576,127.100115', '37.444135,126.692797', '37.643900,126.894571', '37.509454,126.880425', '37.271003,126.975392', '37.443609,127.144521', '37.553878,127.073516', '37.425968,126.666178', '37.549144,126.674639', '37.832668,127.512116', '36.988063,127.142629', '37.292083,127.070000', '38.089184,127.272418', '37.513448,126.907724', '37.570389,126.929628', '37.558086,126.944504', '37.553910,126.918985']
완료1
['37.384532,126.645656', '37.342152,126.730792', '37.404763,126.722968', '37.496645,126.769864', '37.252109,127.074216', '37.320881,126.831077', '37.394613,126.921797', '37.273035,126.950265', '37.500335,127.037596', '37.609643,127.159930', '37.621298,127.024902', '37.257198,127.026007', '37.513093,127.031353', '37.533120,126.640323', '37.493656,126.724134', '37.329829,127.118405', '37.620895,126.838836', '37.638099,126.833358', '37.377235,126.955595', '37.675936,126.748116', '37.643440,127.039413', '37.454866,126.679934', '37.644355,126.936524', '37.486581,127.127495', '37.476412,126.925691', '37.302677,127.079417', '37.539776,126.869079', '37.739252,127.046582', '37.482717,126.949951', '37.469371,126.901246', '37.411694,126.662205', '37.817819,127.089813', '37.551325,126.858411', '37.269945,127.157540', '36.997315,127.100913', '37.450744,126.710499', '37.403080,126.965817', '37.607493,127.135196', '37.534692,127.074327', '37.530552,126.726859', '37.659408,127.116765', '37.654307,126.681501', '37.489897,126.491849', '37.644653,126.766178', '37.538358,126.847336', '37.483974,126.974999', '37.495752,126.755957', '37.492900,126.886427', '37.235585,127.203674', '37.695744,126.743289', '37.558584,126.934113', '37.720182,127.206285', '37.277083,127.118730', '37.644500,126.786140', '37.410279,127.136318', '37.297806,127.048455', '37.671126,126.761620', '37.639388,127.017183', '37.343651,127.115831', '37.569138,126.812192', '37.570749,127.068233', '37.517302,127.104967', '37.905694,127.056669', '37.524659,126.963299', '37.503478,126.553969', '37.318759,127.062055', '37.502816,127.010493', '37.486509,127.040738', '37.488514,127.016222', '37.512792,127.053085', '37.494970,126.851409', '37.605253,126.929107', '37.469235,126.822368', '37.522893,127.028589', '37.299724,127.015538', '37.381670,127.133860', '37.544661,127.046772', '37.268422,126.987411', '37.606151,126.723874', '37.323259,126.846872', '37.598415,127.020288', '37.579797,127.053848', '37.563317,126.910870', '37.830702,127.143594', '37.467073,127.142925', '37.566092,126.830395', '37.517028,126.702209', '37.531338,127.129174', '37.237878,127.190672', '37.467383,126.666387', '37.612276,126.922850', '37.269442,127.025008', '37.293490,127.147352', '37.779440,126.704771', '37.611266,127.077829', '37.424062,126.652109', '37.442015,126.663750', '37.206884,127.039407', '37.266765,127.106933', '37.221344,126.959183', '37.635123,127.032072', '37.513667,127.016166', '37.524371,126.925958', '37.589907,126.683700', '37.544655,127.089493', '37.656327,127.307680', '37.297648,126.977745', '37.104534,126.916966', '37.638168,126.710953', '37.433173,127.136241', '37.384354,127.108486', '37.255024,127.110297', '37.559076,127.035869', '37.642888,126.626692', '37.491515,127.491608', '37.480629,126.864415', '37.867703,126.775760', '37.187576,127.100115', '37.444135,126.692797', '37.643900,126.894571', '37.509454,126.880425', '37.271003,126.975392', '37.443609,127.144521', '37.553878,127.073516', '37.425968,126.666178', '37.549144,126.674639', '37.832668,127.512116', '36.988063,127.142629', '37.292083,127.070000', '38.089184,127.272418', '37.513448,126.907724', '37.570389,126.929628', '37.558086,126.944504', '37.553910,126.918985']
완료2

완료2
완료2
완료2
완료2
완료2
완료2
완료2
완료2
완료3
완료4
완료2
완료2
완료3
완료4
완료2
완료2
완료2
완료2
완료2
완료2
완료2
완료2
완료2
완료2
완료2
완료2
완료2
완료2
완료3
완료4
{'37.500335,127.037596': 3589, '37.621298,127.024902': 3344, '37.476412,126.925691': 3439}
               distance  공원 영화관 초등학교             공시가격                    좌표  \
비교                  0.0  32  13   15  [0, 3000000000]  37.546475,126.964692
서울특별시 강남구 역삼동  1.222601  11   8    2      819200531.3  37.500335,127.037596
서울특별시 강북구 미아동  1.240724   7   4    7      461559225.9  37.621298,127.024902
서울특별시 관악구 신림동  1.336064   6   1   11      443031953.8  37.476412,126.925691

                교통편
비교             3600
서울특별시 강남구 역삼동  3589
서울특별시 강북구 미아동  3344
서울특별시 관악구 신림동  3439

<ipython-input-83-154edd1a8e19>:123: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  comp['교통편'][i+1]= trans[i]
<ipython-input-83-154edd1a8e19>:124: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  comp['교통편'][0] = transit[1]*60

In [35]:
comp

                  distance  공원 영화관         공시가격                    좌표   교통편
비교                     0.0  32  13       [1, 3]  37.546475,126.964692  3600
경기도 고양시 일산동구 백석동  1.228927   4   3  191598465.0  37.644500,126.786140  3351
서울특별시 중구 을지로6가    1.301708   1   3  193672391.3  37.566868,127.006310  1540
서울특별시 강북구 수유동     1.301708   1   3  293740725.3  37.639388,127.017183  3076

In [36]:
comp.to_csv('./교통추천결과값4.csv',encoding='euc-kr')